name: Deploy frontend application

'on':
  push:
    branches:
      - main
      - update-html-deployment

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: prepare the docker-compose run
        run: |
          ls -l

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sphink123456/234-deploylab-frontend:latest

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/frontend"

      - name: Deploy frontend (8086)
  uses: appleboy/ssh-action@v1.2.1
  with:
    host: ${{ secrets.HOST_SERVER }}
    username: ${{ secrets.HOST_USER_NAME }}
    key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
    port: 22
    script: |
      cd /home/ubuntu/frontend
      echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # อัปเดต frontend ปัจจุบันที่รันอยู่ (พอร์ต 8086)
      docker compose pull
      docker compose up -d

- name: Deploy frontend (9999)
  uses: appleboy/ssh-action@v1.2.1
  with:
    host: ${{ secrets.HOST_SERVER }}
    username: ${{ secrets.HOST_USER_NAME }}
    key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
    port: 22
    script: |
      cd /home/ubuntu/frontend
      echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # อัปเดต frontend ใหม่ที่พอร์ต 9999
      docker-compose -f docker-compose-prod.yml pull
      docker-compose -f docker-compose-prod.yml up -d

